### ISSUE TITLE
Anyway to add a blog function to Orbiter?

### ISSUE THREAD

**Issue by tyeeman** [kasparsd/orbiter#5]
I'm looking for something like Orbiter with pages and posts but I don't think Orbiter has posts? Can a blog function be added?

**Comment by kasparsd** [comment]
@tyeeman What aspect of blog are you looking for? Orbiter treats all content the same and offers the "autoindex" functionality that can be used for a blog. For example, [here are the source files](https://github.com/kasparsd/viaorbiter.com/tree/master/content/guide) for this ["blog" index page](http://viaorbiter.com/guide) -- notice the use of filename prefixing to ensure the necessary order of posts/pages. You could use timestamps for blog posts, for example.

**Comment by tyeeman** [comment]
Yes, I see there is a blog folder, sorry. Just tried to run Orbiter and I get lots of errors on my localhost running in a subfolder called 'orbiter'. 

![2016-09-11_230500](https://cloud.githubusercontent.com/assets/4469306/18426153/3e4ef5d0-7874-11e6-81c3-d7a32cf3d91a.png)

I don't see a config file. Is there one? yes, I see sample.ini. I can't add any paths to it though? I tried adding RewriteBase /orbiter but no difference.

**Comment by kasparsd** [comment]
@tyeeman Looks like PHP is missing the `$_SERVER['DOCUMENT_URI']`. You also need to create a `cache` folder inside the `orbiter` folder.

**Comment by tyeeman** [comment]
OK, I added

```
$_SERVER['DOCUMENT_URI'] = __DIR__;
```

to top of index.php and got rid of the errors but now the paths to different files look like this - 

```
<ul class="menu">
            <li><a href="http://localhostG:\Tonys Appz\Uwamp\www/">Index</a></li>
            <li><a href="http://localhostG:\Tonys Appz\Uwamp\www/about">About</a></li>
            <li><a href="http://localhostG:\Tonys Appz\Uwamp\www/rss">RSS</a></li>
            <li><a href="http://twitter.com/viaorbiter">@viaOrbiter</a></li>
        </ul>
```
